version: "3.0"

networks:
  rest-api:

services:
  api:
    environment:
      - HTTP_ADDR=:8080
      - LOG_LEVEL=debug
    build:
      dockerfile: ./deployments/docker/go/Dockerfile
      context: ./../
    command: ["./bin/api"]
    ports:
      - 8080:8080
    volumes:
      - ./ /go/src/app
    networks:
      - rest-api