version: "3.0"

networks:
  rest-api:

services:
  api:
    environment:
      - HTTP_ADDR=:8080
      - LOG_LEVEL=debug
      - PG_URL=postgres://postgres:postgres@postgres/app?sslmode=disable
      - PG_MIGRATIONS_PATH=file:///go/src/app/migrations
      - SDN_XML_SOURCE=https://www.treasury.gov/ofac/downloads/sdn.xml
    build:
      dockerfile: ./deployments/docker/go/Dockerfile
      context: ./../
    command: ["./bin/api"]
    ports:
      - 8080:8080
    volumes:
      - /go/src/app ./
    networks:
      - rest-api
    depends_on:
      - postgres
  postgres:
    restart: always
    image: postgres:14
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - rest-api
volumes:
  pg_data:
    driver: local