// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	model "gluck1986/test_work_xml/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// ISdnParser is an autogenerated mock type for the ISdnParser type
type ISdnParser struct {
	mock.Mock
}

// Next provides a mock function with given fields:
func (_m *ISdnParser) Next() (model.SdnParseResponse, bool) {
	ret := _m.Called()

	var r0 model.SdnParseResponse
	var r1 bool
	if rf, ok := ret.Get(0).(func() (model.SdnParseResponse, bool)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() model.SdnParseResponse); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(model.SdnParseResponse)
	}

	if rf, ok := ret.Get(1).(func() bool); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

type mockConstructorTestingTNewISdnParser interface {
	mock.TestingT
	Cleanup(func())
}

// NewISdnParser creates a new instance of ISdnParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewISdnParser(t mockConstructorTestingTNewISdnParser) *ISdnParser {
	mock := &ISdnParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
