// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IUIDCache is an autogenerated mock type for the IUIDCache type
type IUIDCache struct {
	mock.Mock
}

// Add provides a mock function with given fields: _a0
func (_m *IUIDCache) Add(_a0 int) {
	_m.Called(_a0)
}

// Has provides a mock function with given fields: _a0
func (_m *IUIDCache) Has(_a0 int) bool {
	ret := _m.Called(_a0)

	var r0 bool
	if rf, ok := ret.Get(0).(func(int) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

type mockConstructorTestingTNewIUIDCache interface {
	mock.TestingT
	Cleanup(func())
}

// NewIUIDCache creates a new instance of IUIDCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIUIDCache(t mockConstructorTestingTNewIUIDCache) *IUIDCache {
	mock := &IUIDCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
