// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	model "gluck1986/test_work_xml/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// ISdnWriter is an autogenerated mock type for the ISdnWriter type
type ISdnWriter struct {
	mock.Mock
}

// WriteMany provides a mock function with given fields: _a0
func (_m *ISdnWriter) WriteMany(_a0 []model.SdnEntity) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func([]model.SdnEntity) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewISdnWriter interface {
	mock.TestingT
	Cleanup(func())
}

// NewISdnWriter creates a new instance of ISdnWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewISdnWriter(t mockConstructorTestingTNewISdnWriter) *ISdnWriter {
	mock := &ISdnWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
